---
- name: Add mysql user
  sudo: yes
  mysql_user:
    name={{ mysql.db_user }}
    password={{ mysql.db_password }}
    priv=*.*:ALL,GRANT
    state=present
    host="%"

- name: Ensures database exists
  mysql_db:
    name="{{ mysql.db_name }}"
    state="present"

- name: Update mysql config
  sudo: yes
  template:
    src="my.cnf.j2"
    dest="/etc/mysql/my.cnf"
    mode="644"

- name: Restart mysql
  sudo: yes
  service: name=mysql state=restarted
